name: output flow practice

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
           result: ${{steps.get-result.outputs.result}}
        steps:          
          - name: first step
            id : get-result
            run: echo "result=42" >> $GITHUB_OUTPUT



          -  name : second step
             id : step2
             run: echo '${{toJSON(steps)}}'


    dependant-job:
        runs-on: ubuntu-latest
        needs: build
        
    
        steps:
         - name : first step second job
           run: |
            echo '${{needs.build.outputs.result}}'
